###
GET http://localhost:8080/status?status=OK
Authorization: {{token}}

###
POST http://localhost:8080/login
content-type: application/json

{"username":"test","password":"12345"}

###
POST http://localhost:8080/login
content-type: application/json

{"username":"homer","password":"1234"}

###
POST http://localhost:8080/login
content-type: application/json

{"username":"homer","password":"12345"}

###
POST http://localhost:8080/login
content-type: application/json

{"username":"homer","password":"23456"}

###
POST http://localhost:8080/login
content-type: application/json

{"username":"test3","password":"34567"}

###
GET http://localhost:8080/users
Authorization: {{token}}

###
GET http://localhost:8080/users/1
Authorization: {{token}}

###
POST http://localhost:8080/posts
content-type: application/json
Authorization: {{token}}

{"title":"test","content":"authenticated test","userId":2}

###
POST http://localhost:8080/posts
content-type: application/json
Authorization: {{token}}

{"title":"test2","content":"test2","userId":2}

###
GET http://localhost:8080/posts
Authorization: {{token}}

###
GET http://localhost:8080/posts?findByUserId=1
Authorization: {{token}}

###
POST http://localhost:8080/posts/4/comments
content-type: application/json
Authorization: {{token}}

{"comment":"test comment","userId":2}

###
GET http://localhost:8080/posts/4/comments
Authorization: {{token}}